name: TheAPI
main: me.DevTec.TheAPI.Utils.TheAPIUtils.LoaderClass
author: DevTec
website: https://www.spigotmc.org/resources/theapi.72679/
version: 4.9.6
api-version: 1.13
loadbefore: [Residence,MobArena]
softdepend: [TheVault,Vault,PlaceholderAPI]
permissions:
  TheAPI.*:
    default: op
    children:
      TheAPI.Command.*: true
  TheAPI.Command.*:
    default: false
    children:
      TheAPI.Command.Info: true
      TheAPI.Command.Reload: true
      TheAPI.Command.ClearCache: true
      TheAPI.Command.WorldsManager: true
      TheAPI.Command.PluginManager: true
      TheAPI.Command.Invsee: true