name: TheAPI
main: me.devtec.theapi.utils.theapiutils.LoaderClass
author: DevTec
website: https://www.spigotmc.org/resources/72679/
version: 5.9.4
api-version: 1.13
loadbefore: [WorldGuard,Residence,MobArena,SpecializedCrates,GoldenCrates]
softdepend: [Vault,PlaceholderAPI]
permissions:
  TheAPI.*:
    default: op
    children:
      TheAPI.Command.*: true
  TheAPI.Command.*:
    default: false
    children:
      TheAPI.Command.Info: true
      TheAPI.Command.Reload: true
      TheAPI.Command.ClearCache: true
      TheAPI.Command.WorldsManager: true
      TheAPI.Command.PluginManager: true
      TheAPI.Command.Test: true
      TheAPI.Command.Invsee: true